name: Build and Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Check out your repository's code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate build date
        id: build_date
        run: echo "::set-output name=BUILD_DATE::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

      - name: Build the Docker image
        run: |
          docker build \
            --file Dockerfile \
            --tag ghcr.io/${{ github.repository_owner }}/hammy-mchamiton:${{ github.run_number }} \
            --tag ghcr.io/${{ github.repository_owner }}/hammy-mchamilton:latest \
            --build-arg BUILD_DATE=${{ steps.build_date.outputs.BUILD_DATE }} \
            .
        env:
          BUILD_DATE: ${{ steps.build_date.outputs.BUILD_DATE }}

      - name: Push the Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/hammy-mchamilton:${{ github.run_number }}
          docker push ghcr.io/${{ github.repository_owner }}/hammy-mchamilton:latest
